### ISSUE TITLE
Random background using Flexicubes

### ISSUE THREAD

**Issue by seakforzq** [nv-tlabs/FlexiCubes#1]
I find that random background color will appear in the training process if using flexicubes instead of DMTet, the rendering engine is nvdiffrast, Is that normal?
<img width="343" alt="Snipaste_2023-09-21_14-09-34" src="https://github.com/nv-tlabs/FlexiCubes/assets/31879153/63973dfb-60a4-4f75-9f9b-fca361b5b787">

**Comment by frankshen07** [comment]
Hi @seakforzq ,

The background color shouldn't depend on the foreground geometry. It depends on how your background color is defined. We do not observe this problem with flexicubes in our pipeline.

**Comment by seakforzq** [comment]
> Hi @seakforzq ,
> 
> The background color shouldn't depend on the foreground geometry. It depends on how your background color is defined. We do not observe this problem with flexicubes in our pipeline.

Thank you,  solved this problem by removing the to_rgb mapping layer.
