### ISSUE TITLE
Neural-network based input

### ISSUE THREAD

**Issue by Dengzhi-USTC** [nv-tlabs/FlexiCubes#2]
Hi， it is is pleasure to enjoy this wonderful work.
I have a question when i test for MLP-based gradient func in the "mesh_with_grad_v, mesh_with_grad_f, _ = fc(x_nx3, sdf_n, cube_fx8, res, grad_func=self.network.gradient)"; Do you have any suggestion.

Thank you very much.

The following is the result:
<img width="768" alt="image" src="https://github.com/nv-tlabs/FlexiCubes/assets/39289436/9357b5dc-1a52-43ba-afbb-3c63ed7e8a3b">

**Comment by frankshen07** [comment]
Your writing is generally clear, but I made a few minor adjustments for clarity and flow:

Hi @Dengzhi-USTC,

Thank you for your interest in our work!

In this case, I suggest increasing the `qef_reg_scale `value found here: https://github.com/nv-tlabs/FlexiCubes/blob/6111e37c01e42993d3ab2a322ae57a4be253e5ea/flexicubes.py#L67C39-L67C52. This adjustment should help mitigate the issue of vertices being positioned outside the current cube when solving the QEF. However, the results you observe suggest that the normals are noisy. Thus, it might be beneficial to improve the accuracy of the normals by e.g. directly supervising the normals or using alternative methods to compute them, such as the finite difference method.

**Comment by frankshen07** [comment]
Hi @Dengzhi-USTC,

Thank you for your interest in our work!

In this case, I suggest increasing the qef_reg_scale value found here: https://github.com/nv-tlabs/FlexiCubes/blob/6111e37c01e42993d3ab2a322ae57a4be253e5ea/flexicubes.py#L67C39-L67C52. This adjustment should help mitigate the issue of vertices being positioned outside the current cube when solving the QEF. However, the results you observe suggest that the normals are noisy. Thus, it might be beneficial to improve the accuracy of the normals by e.g. directly supervising the normals or using alternative methods to compute them, such as the finite difference method.

**Comment by Dengzhi-USTC** [comment]
Thanks for your suggestions, i will have a try.
