### ISSUE TITLE
How to extract FC from a custom fixed SDF

### ISSUE THREAD

**Issue by KelestZ** [nv-tlabs/FlexiCubes#21]
Hi I'd like to extract Flexicube mesh from a fixed SDF. The ideal shape (marching cube from SDF using trimesh) should look like Fig.1, but using the example/extract_mesh.ipynb, I got a wrong mesh. I'm wondering where could be wrong? For example, how to give grad_func as torch.autograd in FC? My SDF is alpha from NeRF, so inside regions=1, outside regions<1.

<img width="489" alt="image" src="https://github.com/nv-tlabs/FlexiCubes/assets/27111467/e494bcbb-acd4-4d12-8eb2-8875c0b921ac">
<img width="821" alt="image" src="https://github.com/nv-tlabs/FlexiCubes/assets/27111467/ae8f7a8b-eb3c-4aed-a119-9ccfcd1c4b3c">

**Comment by andybak** [comment]
@KelestZ - I was curious about a reply to this. Why did you close it - did you solve it?
