### ISSUE TITLE
FlexiCubes from existing mesh

### ISSUE THREAD

**Issue by HectorAnadon** [nv-tlabs/FlexiCubes#3]
Hello! First of all, congrats on the fantastic project!

Is it possible to create FlexiCubes from an existing mesh that I want to optimize further?

Thank you!

**Comment by frankshen07** [comment]
Hi @HectorAnadon , thank you for trying out our work!

To initialize FlexiCubes from an existing mesh, you can simply replace the random initialization (e.g. [here](https://github.com/nv-tlabs/FlexiCubes/blob/6111e37c01e42993d3ab2a322ae57a4be253e5ea/examples/optimize.py#L64)) to SDF values computed from the mesh. You can use [this function](https://github.com/nv-tlabs/FlexiCubes/blob/6111e37c01e42993d3ab2a322ae57a4be253e5ea/examples/optimize.py#L112) for SDF computation.

**Comment by nsarafianos** [comment]
Hi @frankshen07 thanks a lot for this amazing work and for releasing the code. 

I'm trying to do what you suggested using the block.obj provided as an example as shown below where `sample_mesh_points` is a small variant of `sample_random_points` that returns the same points and not n//2 + 500. However the result does not look correct (basically it's a denser random grid). Do you have any insights on how to proceed to get FlexiCubes from the block.obj?

Thank you!

```
fc = FlexiCubes(device)
x_nx3, cube_fx8 = fc.construct_voxel_grid(FLAGS.voxel_grid_res)
x_nx3 *= 2

# Load mesh 
block_mesh = load_mesh("data\\inputmodels\\block.obj", device)
block_mesh.auto_normals()

# Sample Points and Compute SDF
pts = sample_mesh_points(x_nx3[:,0].shape[0], block_mesh)
sdf = compute_sdf(pts, block_mesh.vertices, block_mesh.faces) - 0.1
sdf = torch.nn.Parameter(sdf.clone().detach(), requires_grad=True)
```

**Comment by frankshen07** [comment]
Hi @nsarafianos , thanks for trying out our code!

In this case, you want to compute the exact SDF value at grid vertices, `x_nx3`, instead of sampled points. It should be:
`sdf = compute_sdf(x_nx3, block_mesh.vertices, block_mesh.faces)`
