### ISSUE TITLE
Which meshes are used for evaluation in the paper?

### ISSUE THREAD

**Issue by rasaford** [nv-tlabs/FlexiCubes#4]
Dear FlexiCubes authors, 
first of all thanks this great work! I wanted to reproduce your results in Table 2 of the paper and downloaded the dataset by Myles et al. However, in the paper you state that you only use 79 of these shapes for evaluation. 
Could you provide a list of the exact ones used?

And how exactly do you compute the scores listed in that table? I found a script by NDC which gives similar numbers:
https://github.com/czq142857/NDC/blob/main/eval_100000.py
Is that the correct one? 

Many Thanks!

**Comment by frankshen07** [comment]
Hi @rasaford ,

Sorry for the delayed reply. Here is the [list](https://drive.google.com/file/d/1owHSvuJs5097n3UIvE7uhEt6br95fRgZ/view?usp=share_link) of 79 shapes we used for evaluation.

We computed the scores using the same script provided by NDC. Please note that we modified some parameters of the metrics, as detailed in the supplement. Additionally, the ground truth shapes have been normalized to a box of [-0.9, 0.9].

**Comment by rasaford** [comment]
thanks!

**Comment by rasaford** [comment]
Dear authors,

thanks for providing the list of meshes used for evaluation. I was able to reproduce your results in terms of chamfer distance at 64^3 grid resolution. However, I am unable to reproduce the other metrics with the parameters you mentioned above in the supplementary materials:

  | chamfer2 | recall | precision | f1 | echamfer2 | erecall | eprecision | ef1
-- | -- | -- | -- | -- | -- | -- | -- | --
Marching Cubes | 5.22 | 0.32 | 0.32 | 0.32 | 17.57 | 0.02 | 0.01 | 0.26
DMTet | 5.23 | 0.33 | 0.33 | 0.33 | 19.67 | 0.02 | 0.01 | 0.24
FlexiCubes | 4.87 | 0.36 | 0.36 | 0.36 | 23.34 | 0.05 | 0.02 | 0.25

Am I understanding correctly that you're using the following parameters in https://github.com/czq142857/NDC/blob/main/eval_100000.py?
```
sample_num = 100000
f1_threshold = 0.003
ef1_radius = 0.004
ef1_dotproduct_threshold = 0.2
ef1_threshold = 0.005
```

**Comment by frankshen07** [comment]
Apologize for the confusion. Can you try the following parameters for evaluation:
```
sample_num = 100000
f1_threshold = 0.005
ef1_radius = 0.02
ef1_dotproduct_threshold = 0.2
ef1_threshold = 0.005
```

**Comment by rasaford** [comment]
Thanks! Using those parameters, I can get close to your results:

method | chamfer2 | recall | precision | f1 | echamfer2 | erecall | eprecision | ef1
-- | -- | -- | -- | -- | -- | -- | -- | --
Marching Cubes | 5.22 | 0.66 | 0.66 | 0.66 | 1.18 | 0.22 | 0.19 | 0.26
DMTet | 5.23 | 0.67 | 0.67 | 0.67 | 2.23 | 0.28 | 0.25 | 0.32
FlexiCubes | 4.87 | 0.69 | 0.69 | 0.69 | 3.55 | 0.38 | 0.31 | 0.39
